NewOnlineNoticeBoard/Controllers/LogInPageController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using NewOnlineNoticeBoard.Models;
using System.Web.Mvc;
using System.IO;
using System.Runtime.CompilerServices;
using System.Web.Services.Description;

namespace NewOnlineNoticeBoard.Controllers
{
    public class LogInPageController : Controller
    {
        private NewONB db = new NewONB();
        // GET: LogInPage
        public ActionResult AdminLogIn()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdminLogIn(NewAdmin newAdmin)
        {
            var uname = newAdmin.Username;
            var passwd = newAdmin.Password;
            var que = db.NewAdmins.Where(s => s.Username == uname).FirstOrDefault();
            if(que!=null)
            {
                if(que.Password ==passwd)
                { 
                    Session["DeptOfAdmin"] = que.Department;
                    return RedirectToAction("AdminCanSelect");
                }
                else
                {
                    ViewBag.pass = "Invalid Password";
                    return View();
                }
            }
            else
            {
                ViewBag.uname = "Invalid Username";
                return View();
            }
        }

        public ActionResult AdminCanSelect()
        {
            if (Session["DeptOfAdmin"] != null)
            {
                ViewBag.DeptOfAdmin = Session["DeptOfAdmin"];
                var temp = Session["DeptOfAdmin"];

                List<SelectListItem> Notices = null;
                var Item = (from s in db.TypeOfnotices
                            where s.Department == temp
                            select new SelectListItem
                            {
                                Text = s.NoticeType,
                                Value = s.NoticeType
                            }).Distinct();
                Notices = Item.ToList();
                ViewData["Notices"] = Notices;

                return View();
            }
            else
            {
                return RedirectToAction("AdminLogIn");
            }
        }

        public ActionResult DisplayNotice()
        {
            var dept = (string)Session["DeptOfAdmin"];
            ViewBag.dept = dept;
            if (dept == "CE")
            {
                return RedirectToAction("DisplayCeNotice");
            }
            else if(dept == "IT")
            {
                return RedirectToAction("DisplayItNotice");
            }
            else if(dept == "IC")
            {
                return RedirectToAction("DisplayIcNotice");
            }
            else if(dept == "EC")
            {
                return RedirectToAction("DisplayEcNotice");
            }
            else if(dept == "CH")
            {
                return RedirectToAction("DisplayChNotice");
            }
            else if(dept == "MH")
            {
                return RedirectToAction("DisplayMhNotice");
            }
            else
            {
                return RedirectToAction("AdminLogin");
            }
        }
        
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult DisplayNotice(HttpPostedFileBase file,FormCollection notice)
        { 
            if (Request.Files.Count > 0)
            {
                if (file != null)
                {
                    var filename = Path.GetFileName(file.FileName);
                    file.SaveAs(Server.MapPath("~/uploads/" + filename));
                    var dept = (string)Session["DeptOfAdmin"];
                    ViewBag.dept = dept;
                    string title = notice["Title"];
                    DateTime dateofnotice = DateTime.Parse(notice["date"]);
                    string noticetype = Convert.ToString(notice["NoticeType"]);
                    if (dept == "CE")
                    {
                        CE_Notice record = new CE_Notice()
                        {
                            TitleOfNotice = title,
                            date = dateofnotice,
                            NoticeType = noticetype,
                            FileName = filename
                        };
                        db.CE_Notices.Add(record);
                        db.SaveChanges();


                        return RedirectToAction("DisplayCeNotice");

                    }
                    else if(dept == "IT")
                    {
                        IT_Notice record = new IT_Notice()
                        {
                            TitleOfNotice = title,
                            date = dateofnotice,
                            NoticeType = noticetype,
                            FileName = filename
                        };
                        db.IT_Notices.Add(record);
                        db.SaveChanges();
                        return RedirectToAction("DisplayItNotice");
                    }
                    else if (dept == "IC")
                    {
                        IC_Notice record = new IC_Notice()
                        {
                            TitleOfNotice = title,
                            date = dateofnotice,
                            NoticeType = noticetype,
                            FileName = filename
                        };
                        db.IC_Notices.Add(record);
                        db.SaveChanges();
                        return RedirectToAction("DisplayIcNotice");
                    }
                    else if (dept == "EC")
                    {
                        EC_Notice record = new EC_Notice()
                        {
                            TitleOfNotice = title,
                            date = dateofnotice,
                            NoticeType = noticetype,
                            FileName = filename
                        };
                        db.EC_Notices.Add(record);
                        db.SaveChanges();
                        return RedirectToAction("DisplayEcNotice");
                    }
                    else if (dept == "CH")
                    {
                        CH_Notice record = new CH_Notice()
                        {
                            TitleOfNotice = title,
                            date = dateofnotice,
                            NoticeType = noticetype,
                            FileName = filename
                        };
                        db.CH_Notices.Add(record);
                        db.SaveChanges();
                        return RedirectToAction("DisplayChNotice");
                    }
                    else if (dept == "MH")
                    {
                        MH_Notice record = new MH_Notice()
                        {
                            TitleOfNotice = title,
                            date = dateofnotice,
                            NoticeType = noticetype,
                            FileName = filename
                        };
                        db.MH_Notices.Add(record);
                        db.SaveChanges();
                        return RedirectToAction("DisplayMhNotice");
                    }
                    else
                    {

                    }
                    return View();
                }
                else
                {
                    ViewBag.msg = "File not uploaded successfully";
                    return View();
                }
            }
            return View();
        }

        public ActionResult DisplayCeNotice()
        {
            if (Session["DeptOfAdmin"] != null)
            {
                List<CE_Notice> CeNotices = new List<CE_Notice>();
                CeNotices = (List<CE_Notice>)db.CE_Notices.Select(s => s).ToList();
                return View(CeNotices);
            }
            else
            {
                return RedirectToAction("AdminLogIn");
            }
        }

        public ActionResult DisplayItNotice()
        {
            if (Session["DeptOfAdmin"] != null)
            {
                List<IT_Notice> ItNotices = new List<IT_Notice>();
                ItNotices = (List<IT_Notice>)db.IT_Notices.Select(s => s).ToList();
                return View(ItNotices);
            }
            else
            {
                return RedirectToAction("AdminLogIn");
            }
        }

        public ActionResult DisplayEcNotice()
        {
            if (Session["DeptOfAdmin"] != null)
            {
                List<EC_Notice> EcNotices = new List<EC_Notice>();
                EcNotices = (List<EC_Notice>)db.EC_Notices.Select(s => s).ToList();
                return View(EcNotices);
            }
            else
            {
                return RedirectToAction("AdminLogIn");
            }
        }

        public ActionResult DisplayIcNotice()
        {
            if (Session["DeptOfAdmin"] != null)
            {
                List<IC_Notice> IcNotices = new List<IC_Notice>();
                IcNotices = (List<IC_Notice>)db.IC_Notices.Select(s => s).ToList();
                return View(IcNotices);
            }
            else
            {
                return RedirectToAction("AdminLogIn");
            }
        }

        public ActionResult DisplayChNotice()
        {
            if (Session["DeptOfAdmin"] != null)
            {
                List<CH_Notice> ChNotices = new List<CH_Notice>();
                ChNotices = (List<CH_Notice>)db.CH_Notices.Select(s => s).ToList();
                return View(ChNotices);
            }
            else
            {
                return RedirectToAction("AdminLogIn");
            }
        }

        public ActionResult DisplayMhNotice()
        {
            if (Session["DeptOfAdmin"] != null)
            {
                List<MH_Notice> MhNotices = new List<MH_Notice>();

NewOnlineNoticeBoard/Controllers/TypeOfNoticeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewOnlineNoticeBoard;
using NewOnlineNoticeBoard.Models;

namespace NewOnlineNoticeBoard.Controllers
{
    public class TypeOfNoticeController : Controller
    {
        private NewONB db = new NewONB();

        // GET: TypeOfNotice/Create
        public ActionResult Create()
        {
            ViewBag.DeptOfAdmin = Request.QueryString["DeptOfAdmin"].ToString();
            return View();
        }

        // POST: TypeOfNotice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TypeOfNotice typeOfNotice)
        {
            if (ModelState.IsValid)
            {
                var type = typeOfNotice.NoticeType.ToString();
                var dept = typeOfNotice.Department.ToString();
                TypeOfNotice notice = new TypeOfNotice() { NoticeType = type , Department = dept};
                db.TypeOfnotices.Add(notice);
                db.SaveChanges();
                return Redirect("~/LogInPage/AdminCanSelect");
            }

            return View(typeOfNotice);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NewOnlineNoticeBoard/Views/LogInPage/AdminCanSelect.cshtml
@model NewOnlineNoticeBoard.Models.TypeOfNotice

@{
    ViewBag.Title = "AdminCanSelect";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AdminCanSelect</h2>

@using (Html.BeginForm("DisplayNotice", "LogInPage", FormMethod.Post, new { enctype = "multipart/form-data",data_ajax = "false" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Notice Title", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Title","",new { @class="form-control" , required="required"})
                @*@Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })*@
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Date",null, new {@type="date", @class = "form-control" , required="required" })
                @*@Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.Label("NoticeType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NoticeType",(IEnumerable<SelectListItem>)ViewData["Notices"],htmlAttributes: new { @class = "form-control" , required="required"})
                @Html.ActionLink("Add New Type","Create","TypeOfNotice",new { DeptOfAdmin = ViewBag.DeptOfAdmin },new { @class = "btn btn-primary"})
                @*@Html.ValidationMessageFor(model => model.NoticeType, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
                @Html.Label("File",new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.TextBox("file","", new { type = "file" })*@
                    <input type="file" name="file" required/>
                    @*@Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })*@
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
                @Html.ActionLink("See Notices", "DisplayNotice", "LogInPage", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}

NewOnlineNoticeBoard/Views/LogInPage/AdminLogIn.cshtml
@model NewOnlineNoticeBoard.Models.NewAdmin

@{
    ViewBag.Title = "LoginDisplay";
}

@using (Html.BeginForm("AdminLogIn","LogInPage",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("Username",null, new { @class = "form-control" , required = "required"})
                <label class="alert-danger">@ViewBag.uname</Label>
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Password("Password", null, new { @class = "form-control" , required = "required"})
                <label class="alert-danger">@ViewBag.pass</label>
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="LogIn" class="btn btn-default" />
            </div>
        </div>
    </div>
}

NewOnlineNoticeBoard/Views/LogInPage/DisplayCeNotice.cshtml
@model IEnumerable<NewOnlineNoticeBoard.Models.CE_Notice>

@{
    ViewBag.Title = "DisplayCeNotice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayCeNotice</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TitleOfNotice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoticeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleOfNotice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoticeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                <a href="~/NoticeToUser/Download?file=@item.FileName" class="btn btn-primary">Download</a>
                <a href="~/LogInPage/DeleteNotice?id=@item.NoticeId" class="btn btn-primary">Delete</a>
            </td>
        </tr>
    }
    <tr>
        <td>
            <a href="~/LogInPage/AdminCanSelect" class="btn btn-success">Add new Notice</a>
        </td>
    </tr>

</table>

NewOnlineNoticeBoard/Views/LogInPage/DisplayChNotice.cshtml
@model IEnumerable<NewOnlineNoticeBoard.Models.CH_Notice>

@{
    ViewBag.Title = "DisplayChNotice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayChNotice</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TitleOfNotice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoticeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleOfNotice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoticeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                <a href="~/NoticeToUser/Download?file=@item.FileName" class="btn btn-primary">Download</a>
                <a href="~/LogInPage/DeleteNotice?id=@item.NoticeId" class="btn btn-primary">Delete</a>
            </td>
        </tr>
    }
    <tr>
        <td>
            <a href="~/LogInPage/AdminCanSelect" class="btn btn-success">Add new Notice</a>
        </td>
    </tr>

</table>

NewOnlineNoticeBoard/Views/LogInPage/DisplayEcNotice.cshtml
@model IEnumerable<NewOnlineNoticeBoard.Models.EC_Notice>

@{
    ViewBag.Title = "DisplayEcNotice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayEcNotice</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TitleOfNotice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoticeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleOfNotice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoticeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                <a href="~/NoticeToUser/Download?file=@item.FileName" class="btn btn-primary">Download</a>
                <a href="~/LogInPage/DeleteNotice?id=@item.NoticeId" class="btn btn-primary">Delete</a>
            </td>
        </tr>
    }
    <tr>
        <td>
            <a href="~/LogInPage/AdminCanSelect" class="btn btn-success">Add new Notice</a>
        </td>
    </tr>

</table>

NewOnlineNoticeBoard/Views/LogInPage/DisplayIcNotice.cshtml
@model IEnumerable<NewOnlineNoticeBoard.Models.IC_Notice>
@{
    ViewBag.Title = "DisplayIcNotice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayIcNotice</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TitleOfNotice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoticeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleOfNotice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoticeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                <a href="~/NoticeToUser/Download?file=@item.FileName" class="btn btn-primary">Download</a>
                <a href="~/LogInPage/DeleteNotice?id=@item.NoticeId" class="btn btn-primary">Delete</a>
            </td>
        </tr>
    }
    <tr>
        <td>
            <a href="~/LogInPage/AdminCanSelect" class="btn btn-success">Add new Notice</a>
        </td>
    </tr>

</table>

NewOnlineNoticeBoard/Views/LogInPage/DisplayItNotice.cshtml
@model IEnumerable<NewOnlineNoticeBoard.Models.IT_Notice>

@{
    ViewBag.Title = "DisplayItNotice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayItNotice</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TitleOfNotice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoticeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleOfNotice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoticeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                <a href="~/NoticeToUser/Download?file=@item.FileName" class="btn btn-primary">Download</a>
                <a href="~/LogInPage/DeleteNotice?id=@item.NoticeId" class="btn btn-primary">Delete</a>
            </td>
      </tr>
    }
    <tr>
        <td>
            <a href="~/LogInPage/AdminCanSelect" class="btn btn-success">Add new Notice</a>
        </td>
    </tr>

</table>

NewOnlineNoticeBoard/Views/LogInPage/DisplayMhNotice.cshtml
@model IEnumerable<NewOnlineNoticeBoard.Models.MH_Notice>

@{
    ViewBag.Title = "DisplayMhNotice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayMhNotice</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TitleOfNotice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoticeType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleOfNotice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoticeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                <a href="~/NoticeToUser/Download?file=@item.FileName" class="btn btn-primary">Download</a>
                <a href="~/LogInPage/DeleteNotice?id=@item.NoticeId" class="btn btn-primary">Delete</a>
            </td>
        </tr>
    }
    <tr>
        <td>
            <a href="~/LogInPage/AdminCanSelect" class="btn btn-success">Add new Notice</a>
        </td>
    </tr>

</table>

NewOnlineNoticeBoard/Views/LogInPage/DisplayNotice.cshtml
@model IEnumerable<NewOnlineNoticeBoard.Models.CE_Notice>

@{
    ViewBag.Title = "DisplayNotice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DisplayNotice</h2>
@ViewBag.msg
@ViewBag.data


<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TitleOfNotice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoticeType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TitleOfNotice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoticeType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                @*<td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.NoticeId })
                </td>*@
            </tr>
        }
</table>

NewOnlineNoticeBoard/Views/LogInPage/UserLogIn.cshtml
@{
    ViewBag.Title = "LoginDisplay";
}

@using (Html.BeginForm("UserLogIn", "LogInPage", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("EmailId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("emailid", null, new { @class = "form-control" , required = "required"})
                <label class="alert-danger">@ViewBag.useremail</label>
                @*@Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Password", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Password("Password", null, new { @class = "form-control" , required = "required" })
                <label class="alert-danger">@ViewBag.pass</label>
                @*@Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="LogIn" class="btn btn-default" />
            </div>
        </div>
    </div>
}